name: Kubeconform
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  KUBECONFORM_VERSION: v0.6.3
  GKE_MINIMUM: 1.24.15
  GKE_MAXIMUM: 1.27.4

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install kubeconform
        run: >
          mkdir tools && cd tools &&
          curl -L -O https://github.com/yannh/kubeconform/releases/download/${KUBECONFORM_VERSION}/kubeconform-linux-amd64.tar.gz && tar zxvf kubeconform-linux-amd64.tar.gz
      - name: Check Earliest GKE version
        run: >
          ./tools/kubeconform
          --kubernetes-version ${GKE_MINIMUM}
          --summary
          --strict
          --output pretty
          --ignore-filename-pattern cloudbuild.yaml
          --ignore-filename-pattern ".*\.json"
          --ignore-filename-pattern "/helm"
          --ignore-filename-pattern kustomization.yaml
          --ignore-filename-pattern "\.github/"
          --ignore-filename-pattern alert-policy.yaml
          --ignore-filename-pattern dashboard.yaml
          --ignore-missing-schemas
          testdata/
      - name: Check Latest GKE version
        if: ${{ always() }}
        run: >
          ./tools/kubeconform
          --kubernetes-version ${GKE_MAXIMUM}
          --summary
          --strict
          --output pretty
          --ignore-filename-pattern cloudbuild.yaml
          --ignore-filename-pattern ".*\.json"
          --ignore-filename-pattern "/helm"
          --ignore-filename-pattern kustomization.yaml
          --ignore-filename-pattern "\.github/"
          --ignore-filename-pattern alert-policy.yaml
          --ignore-filename-pattern dashboard.yaml
          --ignore-missing-schemas
          testdata/
